version: 0.2

env:
  shell: bash
  variables:
     HUGO_VERSION: 0.114.0
     DART_SASS_VERSION: 1.63.5
phases:
  install:
    runtime-versions:
      golang: 1.20
      nodejs: 18
    commands:
      # Install Dart Sass
      - curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz
      - tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz
      - cp -r dart-sass/* /codebuild/user/bin
      - rm -rf dart-sass*
      # Install Hugo
      - curl -LJO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
      - apt install -y ./hugo_extended_${HUGO_VERSION}_linux-amd64.deb
      - rm hugo_extended_${HUGO_VERSION}_linux-amd64.deb
  pre_build:
    commands:
      # Install Node.js dependencies
      - "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
  build:
    commands:
      - hugo --gc --minify
artifacts:
  files:
    - '**/*'
  base-directory: 'public'
