version: 0.2

env:
  shell: bash
  variables:
     HUGO_VERSION: 0.113.0
     DART_SASS_VERSION: 1.62.1
phases:
  install:
    runtime-versions:
      golang: 1.20
      nodejs: 18
    commands:
      # Install Embedded Dart Sass
      - curl -LJO https://github.com/sass/dart-sass-embedded/releases/download/${DART_SASS_VERSION}/sass_embedded-${DART_SASS_VERSION}-linux-x64.tar.gz
      - tar -xf sass_embedded-${DART_SASS_VERSION}-linux-x64.tar.gz
      - cp -r sass_embedded/ /codebuild/user/bin/dart-sass-embedded
      - PATH=$PATH:/codebuild/user/bin/dart-sass-embedded
      # Install Hugo
      - curl -L -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
      - dpkg -i hugo.deb
      - hugo env
  pre_build:
    commands:
      # Install Node.js dependencies
      - "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
  build:
    commands:
      - hugo --gc --minify
artifacts:
  files:
    - '**/*'
  base-directory: 'public'
